# Generated by Django 2.1 on 2018-08-25 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentround',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='pair.Tournament'),
        ),
    ]
