# Generated by Django 2.1 on 2018-08-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0003_auto_20180825_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pair.TournamentRound'),
        ),
        migrations.AlterField(
            model_name='roundresult',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player2', to='pair.Participant'),
        ),
        migrations.AlterField(
            model_name='roundresult',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player1', to='pair.Participant'),
        ),
        migrations.AlterField(
            model_name='roundresult',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pair.Tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='pair.Tournament'),
        ),
    ]
