# Generated by Django 2.0 on 2019-06-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0004_auto_20180827_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tournamentround',
            name='pairing_system',
            field=models.CharField(choices=[['ROUND_ROBIN', 'Round Robin'], ['SWISS', 'Swiss'], ['KOTH', 'KOTH'], ['RANDOM', 'Random'], ['MANUAL', 'Manual']], max_length=16),
        ),
    ]
