# Generated by Django 2.2.2 on 2019-09-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0006_auto_20190918_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='national_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='wespa_rating',
            field=models.IntegerField(null=True),
        ),
    ]
