# Generated by Django 2.2.2 on 2019-09-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0007_auto_20190918_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='national_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wespa_games',
            field=models.IntegerField(default=0),
        ),
    ]
