# Generated by Django 2.2.2 on 2019-12-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0008_auto_20190918_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_national',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='last_wespa',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
