# Generated by Django 2.2.2 on 2019-12-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0009_auto_20191226_0553'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('player', 'tournament')},
        ),
    ]
